import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'sensor_service.dart';

class PdfService {
  static Future<void> exportReport() async {
    final pdf = pw.Document();

    final sensor = SensorService.instance;

    final date =
    DateFormat('dd/MM/yyyy  HH:mm:ss').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,

        build: (context) => [


          /// HEADER


          pw.Center(
            child: pw.Column(
              children: [

                pw.Text(
                  "SMART WINDOW IoT SYSTEM",
                  style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue,
                  ),
                ),

                pw.SizedBox(height: 5),

                pw.Text(
                  "Sensor Monitoring Report",
                  style: const pw.TextStyle(
                    fontSize: 16,
                  ),
                ),

              ],
            ),
          ),

          pw.SizedBox(height: 20),

          pw.Divider(),

          pw.Text(
            "Generated Date : $date",
            style: const pw.TextStyle(
              fontSize: 12,
            ),
          ),

          pw.Divider(),

          pw.SizedBox(height: 20),


          /// SENSOR TABLE


          pw.Text(
            "Current Sensor Status",
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
            ),
          ),

          pw.SizedBox(height: 15),

          pw.Table(
            border: pw.TableBorder.all(),

            children: [

              tableRow(
                "Temperature",
                "${sensor.temperature.toStringAsFixed(1)} °C",
              ),

              tableRow(
                "Humidity",
                "${sensor.humidity.toStringAsFixed(1)} %",
              ),

              tableRow(
                "Rain Sensor",
                sensor.rain
                    ? "Detected"
                    : "No Rain",
              ),

              tableRow(
                "Smoke Sensor",
                sensor.smoke
                    ? "Detected"
                    : "Normal",
              ),

              tableRow(
                "Window Status",
                sensor.windowOpen
                    ? "OPEN"
                    : "CLOSED",
              ),

            ],
          ),

          pw.SizedBox(height: 30),


          /// SYSTEM SUMMARY


          pw.Container(
            width: double.infinity,

            padding: const pw.EdgeInsets.all(15),

            decoration: pw.BoxDecoration(
              border: pw.Border.all(),
            ),

            child: pw.Column(
              crossAxisAlignment:
              pw.CrossAxisAlignment.start,

              children: [

                pw.Text(
                  "System Summary",
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 16,
                  ),
                ),

                pw.SizedBox(height: 10),

                pw.Bullet(
                  text:
                  "Temperature monitoring is active.",
                ),

                pw.Bullet(
                  text:
                  "Humidity monitoring is active.",
                ),

                pw.Bullet(
                  text:
                  "Automatic window control is enabled.",
                ),

                pw.Bullet(
                  text:
                  "Rain and smoke detection are functioning normally.",
                ),

              ],
            ),
          ),

          pw.SizedBox(height: 40),


          /// FOOTER


          pw.Divider(),

          pw.Center(
            child: pw.Column(
              children: [

                pw.Text(
                  "Generated by Smart Window IoT System",
                ),

                pw.Text(
                  "Flutter + ESP32",
                ),

                pw.Text(
                  "Final Year Project",
                ),

              ],
            ),
          ),

        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (_) async => pdf.save(),
    );
  }

  static pw.TableRow tableRow(
      String title,
      String value,
      ) {
    return pw.TableRow(
      children: [

        pw.Padding(
          padding: const pw.EdgeInsets.all(10),
          child: pw.Text(
            title,
            style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),

        pw.Padding(
          padding: const pw.EdgeInsets.all(10),
          child: pw.Text(value),
        ),

      ],
    );
  }
}